name: propcheck
version: 0.2.0
author: Paul Brauner <polux@google.com>
description: A library for exhaustive and randomized testing of Dart properties
homepage: https://code.google.com/p/dart-check/
documentation: http://goo.gl/PlZPl
dependencies:
  enumerators: '>=0.3.0 <0.4.0'
dev_dependencies:
  unittest: any
