name: dart-check
description: A library for exhaustive and randomized testing of Dart properties.
version: 0.0.1
dependencies:
  dart-enumerators:
    git:
      url: https://code.google.com/p/dart-enumerators/
      ref: simpler-api
  unittest:
    sdk: unittest
