name: dart_check
description: A library for exhaustive and randomized testing of Dart properties.
version: 0.0.1
author: Paul Brauner <polux@google.com>
homepage: https://code.google.com/p/dart-check/
dependencies:
  enumerators:
  unittest:
