name: propcheck
version: 0.1.11
author: Paul Brauner <polux@google.com>
description: A library for exhaustive and randomized testing of Dart properties
homepage: https://code.google.com/p/dart-check/
documentation: http://goo.gl/PlZPl
dependencies:
  enumerators: '>=0.2.6 <0.3.0'
dev_dependencies:
  unittest: any
